---
version: 12.5.2
slug: samba
name: Samba share (with mount)
description: Expose Home Assistant folders with SMB/CIFS and additional USB media
url: https://github.com/zachdeibert/hass-samba-with-mount/tree/master/samba
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  username: homeassistant
  password: null
  workgroup: WORKGROUP
  local_master: true
  enabled_shares:
    - addons
    - addon_configs
    - backup
    - config
    - media
    - mnt-backup
    - mnt-media
    - mnt-share
    - share
    - ssl
  compatibility_mode: false
  apple_compatibility_mode: true
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
  fstab: []
schema:
  username: str
  password: password
  workgroup: str
  local_master: bool
  enabled_shares:
    - "match(^(?i:(addons|addon_configs|backup|config|media|mnt-backup|mnt-media|mnt-share|share|ssl))$)"
  compatibility_mode: bool
  apple_compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
  fstab:
    - "match(^\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+[0-9]+\\s+[0-2]$)"
startup: services
privileged:
  - SYS_ADMIN
apparmor: false
